server.port: 4301

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**
        - id: healthrecordandexpertise-service
          uri: lb://healthrecordandexpertise-service
          predicates:
            - Path=/api/v1/healthrecordandexpertise/**
        - id: social-service
          uri: lb://social-service
          predicates:
            - Path=/api/v1/reviews/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/users/**
        - id: physiotherapist-service
          uri: lb://physiotherapist-service
          predicates:
            - Path=/api/v1/physiotherapists/**
        - id: therapy-service
          uri: lb://therapy-service
          predicates:
            - Path=/api/v1/theraphies/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/v1/patients/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
      instance:
      leaseRenewalIntervalInSeconds: 5
      leaseExpirationDurationInSeconds: 5
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  
